language: php

php:
    - "5.5"
    - "5.6"
    - "7.0"

addons:
    postgresql: "9.4"

before_script:
    - composer install
    - psql -c "create role admin login createdb password 'adminpassword' superuser ;" -U postgres
    - psql -c "create role behat login createdb password 'behatpassword';" -U postgres
    - psql -c 'create database behat OWNER=behat;' -U postgres
    - psql -c 'create database dblinker_test OWNER=behat;' -U postgres
    - psql -c 'create database forbidden_db;'
    - mysql -e 'create database dblinker_test;'
    - mysql -e 'create database forbidden_db;'
    - mysql -e 'CREATE USER "behat"@"localhost" IDENTIFIED BY "behatpassword";'
    - mysql -u root -e 'GRANT ALL PRIVILEGES ON dblinker_test.* TO "behat"@"localhost";'
    - mysql -u root -e 'FLUSH PRIVILEGES;'

script:
    - vendor/bin/behat -s $BEHAT_DB_DRIVER --tags $SKIP_TAGS

env:
    - BEHAT_DB_DRIVER=mysqli SKIP_TAGS="~@skip-travis&&~@skip-travis-mysqli" DBLINKER_MYSQL_1_ENV_MYSQL_DATABASE=dblinker_test DBLINKER_MYSQL_1_PORT_3306_TCP_ADDR=127.0.0.1 DBLINKER_MYSQL_1_ENV_MYSQL_USER=behat DBLINKER_MYSQL_1_ENV_MYSQL_PASSWORD=behatpassword DBLINKER_MYSQL_1_ENV_MYSQL_ROOT_PASSWORD=
    - BEHAT_DB_DRIVER=pdo_mysql SKIP_TAGS="~@skip-travis&&~@skip-travis-pdo-mysql" DBLINKER_MYSQL_1_ENV_MYSQL_DATABASE=dblinker_test DBLINKER_MYSQL_1_PORT_3306_TCP_ADDR=127.0.0.1 DBLINKER_MYSQL_1_ENV_MYSQL_USER=behat DBLINKER_MYSQL_1_ENV_MYSQL_PASSWORD=behatpassword DBLINKER_MYSQL_1_ENV_MYSQL_ROOT_PASSWORD=
    - BEHAT_DB_DRIVER=pdo_pgsql SKIP_TAGS="~@skip-travis&&~@skip-travis-pdo-pgsql" DBLINKER_POSTGRESQL_1_ENV_POSTGRES_DATABASE=dblinker_test DBLINKER_POSTGRESQL_1_PORT_5432_TCP_ADDR=127.0.0.1 DBLINKER_POSTGRESQL_1_ENV_POSTGRES_USER=behat DBLINKER_POSTGRESQL_1_ENV_POSTGRES_PASSWORD=behatpassword DBLINKER_POSTGRES_1_ENV_POSTGRES_ROOT_USER=admin DBLINKER_POSTGRES_1_ENV_POSTGRES_ROOT_PASSWORD=adminpassword

matrix:
    fast_finish: true
